name: WooOmni
version: ${project.version}
main: com.oolonghoo.woomni.WooOmni
api-version: '1.21'
author: oolongho
description: A modular basic management plugin
libraries:
  - com.zaxxer:HikariCP:5.1.0
  - com.google.guava:guava:33.0.0-jre

commands:
  wooomni:
    description: Main command
    usage: /wooomni [args]
    permission: wooomni.use
    aliases: [wo, womni]
  fly:
    description: Toggle fly mode
    usage: /fly [player]
    permission: wooomni.fly
  flyspeed:
    description: Set fly speed
    usage: /flyspeed <speed> [player]
    permission: wooomni.flyspeed
  god:
    description: Toggle god mode
    usage: /god [player]
    permission: wooomni.god
  vanish:
    description: Toggle vanish mode
    usage: /vanish [player]
    permission: wooomni.vanish
    aliases: [v]
  vanishlist:
    description: List vanished players
    usage: /vanishlist
    permission: wooomni.vanish.list
    aliases: [vlist, vl]
  vanishedit:
    description: Open vanish settings GUI
    usage: /vanishedit [player]
    permission: wooomni.vanish.edit
    aliases: [ve, vedit]

permissions:
  wooomni.use:
    default: true
  wooomni.admin:
    default: op
  wooomni.reload:
    default: op
  wooomni.fly:
    default: op
  wooomni.fly.other:
    default: op
  wooomni.flyspeed:
    default: op
  wooomni.god:
    default: op
  wooomni.god.other:
    default: op
  wooomni.vanish:
    default: op
  wooomni.vanish.other:
    default: op
  wooomni.vanish.list:
    default: op
  wooomni.vanish.see:
    default: op
  wooomni.vanish.autojoin:
    default: op
  wooomni.vanish.edit:
    default: op
  wooomni.vanish.edit.other:
    default: op
